### ISSUE TITLE
Need to set dynamic merchant Id and Key 

### ISSUE THREAD

**Issue by Nadimuthu** [anandsiddharth/laravel-paytm-wallet#1]
Hi,

My application is working with the multistore concept. So the merchant account will set dynamically based on the Login. I am trying to use your packages in Laravel 5.3 with this option. But could not make it. Please help on this.

**Comment by anandsiddharth** [comment]
Can you upload the screenshot of error and the code snippet.

**Comment by Nadimuthu** [comment]
![image](https://cloud.githubusercontent.com/assets/5688877/21741331/ac5de23a-d4f8-11e6-8ea9-e2c7f7539122.png)

Code:

namespace Anand\LaravelPaytmWallet;

use Illuminate\Support\Manager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Version_1\CommonFactorController;

class PaytmWalletManager extends Manager implements Contracts\Factory{	

	private $config;

	public function with($driver){		
		return $this->driver($driver);
	}

	protected function createReceiveDriver(){
		$this->config = $this->getDynamicMerchantAccount();			
		return $this->buildProvider(
			'Anand\LaravelPaytmWallet\Providers\ReceivePaymentProvider',
			$this->config
			);
	}

	protected function createStatusDriver(){
		$this->config = $this->getDynamicMerchantAccount();
		return $this->buildProvider(
			'Anand\LaravelPaytmWallet\Providers\StatusCheckProvider',
			$this->config
			);
	}

	protected function createBalanceDriver(){
		$this->config = $this->getDynamicMerchantAccount();
		return $this->buildProvider(
			'Anand\LaravelPaytmWallet\Providers\BalanceCheckProvider',
			$this->config
			);
	}

	protected function createAppDriver(){
		$this->config = $this->getDynamicMerchantAccount();
		return $this->buildProvider(
			'Anand\LaravelPaytmWallet\Providers\PaytmAppProvider',
			$this->config
			);
	}
	

	public function getDefaultDriver(){
		throw new \Exception('No driver was specified. - Laravel Paytm Wallet');
	}

	public function buildProvider($provider, $config){

		return new $provider(
			$this->app['request'],
			$config
			);
	}


	private function beginTransaction(){

		$params = [
		'MID' => $this->merchant_id,
		'ORDER_ID' => $this->parameters['order'],
		'CUST_ID' => $this->parameters['user'],
		'INDUSTRY_TYPE_ID' => $this->industry_type,
		'CHANNEL_ID' => $this->channel,
		'TXN_AMOUNT' => $this->parameters['amount'],
		'WEBSITE' => $this->merchant_website
		];

		$this->app['request']->session()->forget('branch_restaurant_id');
		return view('paytmwallet::transact')->with('params', $params)->with('txn_url', $this->paytm_txn_url)->with('checkSum', getChecksumFromArray($params, $this->merchant_key));
	}

	public function getDynamicMerchantAccount(){

		$restaurantId 	= $this->app['request']->session()->get('branch_restaurant_id');		
		$storeInfo 		= app(CommonFactorController::class)->getStoreInformation($restaurantId);
		$merchantInfo 	= app(CommonFactorController::class)->getMerchantAccountDetails($storeInfo->intvendorId);

		$merchantAccountDetails['env'] 				= 'sandbox';
		$merchantAccountDetails['merchant_id'] 		= $merchantInfo->mPTClientId;
		$merchantAccountDetails['merchant_key'] 	= $merchantInfo->mPTclientSecret;
		$merchantAccountDetails['merchant_website'] = 'http://'.$merchantInfo->merchantWebsite.'.sandboxjuzdine.com';
		$merchantAccountDetails['channel'] 			= 'WEB';
		$merchantAccountDetails['industry_type'] 	= $merchantInfo->industryType;

		return $merchantAccountDetails;
	}

}

**Comment by Nadimuthu** [comment]
I have check in the code. I could not make to generate and get the CHECKSUMHASH value. In that case,  checksum value is null. So i got an PHP fatel error exception.

**Comment by anandsiddharth** [comment]
dude you need to install this package using composer

**Comment by Nadimuthu** [comment]
I have installed via composer only. But i was changed the code for my purpose.

**Comment by anandsiddharth** [comment]
Instead you can set merchant credentials before making transactions using the following built in laravel function
`config(['services.paytm-wallet.merchant_id' => 'YOUR_MERCHANT_ID'])`
add this code to your controller where you want to make transaction.

for example:
```
public function makePayment(Request $request){
    config(['services.paytm-wallet.merchant_id' => 'YOUR_MERCHANT_ID']);
    config(['services.paytm-wallet.merchant_key' => 'YOUR_MERCHANT_KEY']);
    config(['services.paytm-wallet.channel' => 'YOUR_MERCHANT_CHANNEL']);
    config(['services.paytm-wallet.industry_type' => 'YOUR_MERCHANT_INDUSTRY_TYPE']);
    $payment = PaytmWallet::with('receive');
    $payment->prepare([
      'order' => 'X',
      'user' => 'X',
      'mobile_number' => 'XXXXXXXXXX',
      'email' => 'XXXXXXXXXXXX@gmail.com',
      'amount' => 'XX',
      'callback_url' => 'http://example.com/callback'
    ]);
    return $payment->receive();
}
```
