### ISSUE TITLE
Class 'Dompdf\Exception' not found

### ISSUE THREAD

**Issue by farazappy** [anandsiddharth/laravel-paytm-wallet#12]
Hey, I'm Getting an error in my callback url!

Controller Code: 

        $transaction = PaytmWallet::with('receive');
        $response = $transaction->response();
        $order_id = $transaction->getOrderId();
        if($transaction->isSuccessful()) {
            Order::where('order_id', $order_id)->update(['payment_status'=>'success','transaction_id'=>$transaction->getTransactionId()]);
            dd('Successfully paid!');
        } else if($transaction->isFailed()) {
            Order::where('order_id', $order_id)->update(['payment_status'=>'failed','transaction_id'=>$transaction->getTransactionId()]); 
            dd('Payment Failed!');
        }

My Route is a post route with CSRF Protection disabled.

Error ->

`(1/1) FatalThrowableError`
`Class 'Dompdf\Exception' not found`
`in PaytmWalletProvider.php (line 50)`
`at PaytmWalletProvider->response()`
`in OrderController.php (line 186)`
`at OrderController->paymentCallback(object(Request))`
`at call_user_func_array(array(object(OrderController), 'paymentCallback'), array(object(Request)))`
`in Controller.php (line 55)`

**Comment by anandsiddharth** [comment]
Hi @farazappy 

This issue is not related to this package. Dompdf is not used in this package. 
In case if you are using Dompdf in your application verify its installation.

If this answer helps please close the issue or attach the screenshots of your error page.

**Comment by farazappy** [comment]
I'm not using Dompdf, It's in your source  file : 

`<?php`
`namespace Anand\LaravelPaytmWallet\Providers;`
`use Dompdf\Exception;`
`use Illuminate\Http\Request;`
`require __DIR__.'/../../lib/encdec_paytm.php';`
`class PaytmWalletProvider{`

To throw checksum did not match exception, I guess.

**Comment by anandsiddharth** [comment]
Hi @farazappy 

My bad.
Released a patch  https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v1.0.6
