### ISSUE TITLE
Errow while checking payment status.

### ISSUE THREAD

**Issue by sshegde123** [anandsiddharth/laravel-paytm-wallet#16]
I was getting error while checking payments. 
vendor/anandsiddharth/laravel-paytm-wallet/src/Providers/StatusCheckProvider.php","message":"Trying to get property of non-object","line":55

After debugging I found couple of  issues in StatusCheckProvider.php
1) Response not coverted to object format.
 Typecast $this->response to object in line no 50 i.e
      public function response(){
		return (object)$this->response;
	}
2) "use Anand\LaravelPaytmWallet\Facades\PaytmWallet;"  this was missing.

This resolved my issue.

**Comment by anandsiddharth** [comment]
You might be using the older version of this package - try updating
