### ISSUE TITLE
Wrong (old) PG URL

### ISSUE THREAD

**Issue by plakhin** [anandsiddharth/laravel-paytm-wallet#18]
According to `APP Integrations` section of [the docs](https://business.paytm.com/developers-api/integration/payment-gateway/overview), production URL should be: ` https://securegw.paytm.in/theia/` Despite the fact everything works for the staging environment, for production `https://secure.paytm.in/oltp-web/` is not usable anymore, as mentioned by Paytm support, and leads to "OOPS Payment failed due to any of these reasons..." page.

How can I change this URL?

**Comment by plakhin** [comment]
Just checked. Changing `https://secure.paytm.in/oltp-web/` to `https://securegw.paytm.in/theia/processTransaction` helped.

**Comment by anandsiddharth** [comment]
Hi,
Is this for app integration, 
please fork the repo and push the code to your branch and create a pull request to main repo.

**Comment by plakhin** [comment]
Nope, this for WEB integration to. Already busy with PR.

**Comment by anandsiddharth** [comment]
cool!
so the production urls are updated you mean to say?

**Comment by anandsiddharth** [comment]
Merged and Released,
https://github.com/anandsiddharth/laravel-paytm-wallet/tree/v1.0.8
Please test it and post here.

Thanks!

**Comment by plakhin** [comment]
Great! Thanks. WIll test now and report.

**Comment by plakhin** [comment]
Just tested. Staging works perfect. Production now redirects to right page, but needs real transaction to be sure everything works well. Asked client to make real transaction to test.
Thank you for assistance.

**Comment by anandsiddharth** [comment]
Thank you! @plakhin Appreciate that.
Will wait for your response.
