### ISSUE TITLE
Paytm Error : OOPS Payment Failed Due To Any Of these Reasons

### ISSUE THREAD

**Issue by armashfankar** [anandsiddharth/laravel-paytm-wallet#2]
'paytm-wallet' => [
    'env' => 'local', // values : (local | production)
    'merchant_id' => '*****',
    'merchant_key' => '*****',
    'merchant_website' => 'WEB_STAGING',
    'channel' => 'WEB',
    'industry_type' => 'Retail',
    ]

![paytm secure online payment gateway](https://cloud.githubusercontent.com/assets/6822592/21739816/a2e08ba8-d4cc-11e6-9075-a7bddb4a4495.png)

**Comment by anandsiddharth** [comment]
Did you provide merchant id & key in your code as provided by paytm

**Comment by armashfankar** [comment]
Yes.

**Comment by anandsiddharth** [comment]
You can set config on the fly even as you wanted to set them up dynamically using this built in laravel function 
`config(['services.paytm-wallet.merchant_id' => 'YOUR_MERCHANT_ID'])`

**Comment by anandsiddharth** [comment]
If you are facing issues with payment gateway, pease paste the snippet of code.

**Comment by armashfankar** [comment]
public function order()
    {
    	
        $payment = PaytmWallet::with('receive');
        $payment->prepare([
          'order' => '1',
          'user' => '1',
          'mobile_number' => '9967031001',
          'email' => 'armashfankar@gmail.com',
          'amount' => '20',
          'callback_url' => 'http://slncn.com/callback'
        ]);
        return $payment->receive();
    }


    public function paymentCallback()
    {
        $transaction = PaytmWallet::with('receive');

        $response = $transaction->response(); // To get raw response as object'
        dd($response);
        //Check out response parameters sent by paytm here -> http://paywithpaytm.com/developer/paytm_api_doc?target=interpreting-response-sent-by-paytm

        if($transaction->isSuccessful()){
          //Transaction Successful
        }else if($transaction->isFailed()){
          //Transaction Failed
        }else if($transaction->isOpen()){
          //Transaction Open/Processing
        }

        //get important parameters via public methods
        $transaction->getOrderId(); // Get order id
        $transaction->getTransactionId(); // Get transaction id
    }

**Comment by anandsiddharth** [comment]
Your code is absolutely correct, you can troubleshoot your code either way:-
1> Try changing the order id.
2> Contact paytm for valid credentials

**Comment by armashfankar** [comment]
i tried by changing order id and it worked.
now issue is for callback.

i am redirected to paytm.
i logged in using demo credentials provided by paytm.
i completed transaction but in callback its showing me error.

![screenshot from 2017-01-07 13 43 37](https://cloud.githubusercontent.com/assets/6822592/21740409/6612b0bc-d4df-11e6-866b-e0c2b4e4d2b3.png)

**Comment by anandsiddharth** [comment]
Try contacting paytm regarding the issue. I can't help you with try using production credentials.

**Comment by golchha21** [comment]
Nothing is working.
