### ISSUE TITLE
How to do recurring payments ?

### ISSUE THREAD

**Issue by hardevine** [anandsiddharth/laravel-paytm-wallet#20]

**Comment by anandsiddharth** [comment]
recurring payments are not yet supported

**Comment by anandsiddharth** [comment]
Hi, I am not able to see any documentation for recurring payments, if you have any information sources and I will also need your merchant staging credentials. Let's make this conversation private beyond this.
Connect with me on Gitter.
https://gitter.im/anandsiddharth

**Comment by aotearoait** [comment]
Has there been any progress on this as it is something we are interested in to for a project. Thanks

**Comment by anandsiddharth** [comment]
No there hasn't been, I don't see any reference to recurring payments. If you have please provide.

**Comment by aotearoait** [comment]
I’m going to have to develop one myself then. As will require in couple of months

Kind Regards
Joel Ireland

________________________________

**Comment by anandsiddharth** [comment]
No! Like I said, I didn't find any reference or docs for recurring payments.

**Comment by aotearoait** [comment]
This link explains use. Full dev api only available for merchants. https://business.paytm.com/developers-api/integration/recurring-payment/overview

**Comment by anandsiddharth** [comment]
You can send those to gitter.im

**Comment by aotearoait** [comment]
Hey mate trying to get ahold of you on gitterim but wont let me direct chat. I have a pdf with all the documentation on recurring payments for you :)

**Comment by kanu786** [comment]
is there any update on recurring payment support?

**Comment by anandsiddharth** [comment]
@kanu786 and others

Recurring payments documentation is confidential to only registered merchants and confidential for them so hence can't be implemented in this package. If you are one of those merchants, please fork and extend and make use of it privately.
