### ISSUE TITLE
Callback URL error

### ISSUE THREAD

**Issue by Aarej** [anandsiddharth/laravel-paytm-wallet#21]
I setup all thing as per your documentation.
But after completing PAYTM  side when I returning then getting error

> Something went wrong. It may be due to any of these reasons:
> Session expired due to inactivity
> Our system encountered an obstacle

> You can fix it yourself! Here's how:
> Check payment status with your bank to avoid double payment
> Clear cookies & temporary internet files of the browser & retry
> Launch a new browser & start from the beginning
> Still unable to transact? visit us at paytm.com/care

 And calback URL is below
 https://securegw.paytm.in/theia/v1/%7B%7Broute(

**Comment by anandsiddharth** [comment]
post relevant piece of code, paste your configuration and paste your controller code and routes

**Comment by Aarej** [comment]
Issue has been resolved .

**Comment by pushpak1300** [comment]
I am also facing same error can you explain how did you solve? @Aarej
