### ISSUE TITLE
Invalid Checksum

### ISSUE THREAD

**Issue by channaveer** [anandsiddharth/laravel-paytm-wallet#24]
Hi I am getting the following issue when using the library. Any help really appriciated.

<img width="1438" alt="screenshot 2018-11-19 at 12 17 41 pm" src="https://user-images.githubusercontent.com/7845383/48690662-7b1fda00-ebf5-11e8-8b52-43bb7a454009.png">

**Comment by anandsiddharth** [comment]
https://github.com/anandsiddharth/laravel-paytm-wallet/issues/23

**Comment by channaveer** [comment]
Okay looking into it.

**Comment by channaveer** [comment]
Hi @anandsiddharth I have added the proper credentials but even then I am having this issue.

**Comment by anandsiddharth** [comment]
This, issue is completely related with keys, please validate or contact paytm, this error is thrown from paytm's sdk, this package is just a wrapper around sdk to plug into laravel easily

**Comment by channaveer** [comment]
Okay thanks will check with them in case if the problem solves then will close the ticket.

**Comment by channaveer** [comment]
Hi @anandsiddharth  I had kept the staging contact number hence it was showing error. Now it's fixed. Thanks for pointing me to right direction.

One more doubt I am having is once I check out the payment page is only showing BHIM option for not logged in users. Is there a way of showing a credit card, debit card and net banking options along with it.

**Comment by anshu2212** [comment]
I had similar problem . You need to call paytm and they will activate the
feature.

**Comment by channaveer** [comment]
@anshu2212  Thank you very much will check with the customer support.

**Comment by anandsiddharth** [comment]
@channaveer you may want to star the package 😸

**Comment by channaveer** [comment]
@anandsiddharth  sure I will. Thanks for your help.

**Comment by devendrakavya** [comment]
i got solution from  #https://www.tutsmake.com/laravel-5-7-paytm-payment-gateway-integration-example/

**Comment by plexdeveloper** [comment]
@anandsiddharth Can you please make the change mentioned in [this link ] (https://www.tutsmake.com/laravel-5-7-paytm-payment-gateway-integration-example/)for the checksum error?

**Comment by devendrakavya** [comment]
Yes we can do it

**Comment by sheikh005** [comment]
> i got solution from #https://www.tutsmake.com/laravel-5-7-paytm-payment-gateway-integration-example/

This solution works well for me. Thanks.

**Comment by gurman8571** [comment]
getting error invalid checksum  but my  all credentials are correct
