### ISSUE TITLE
How can I initiate refund of payments

### ISSUE THREAD

**Issue by cwdabba** [anandsiddharth/laravel-paytm-wallet#25]
Hi, once the order is canceled after the payment is made. I want to initiate a refund of the payment. How can it be done from this package?

If currently not supported then by when we can expect the feature.  If already supporting then please let me know how to integrate the same or any redirect to the resource will be really helpful.

Thanks.

**Comment by anandsiddharth** [comment]
Hi, This feature is currently not available.
For further development of this package I need credentials, staging credentials is more than enough!

**Comment by cwdabba** [comment]
Hi Anand,

Please find my staging credentials

**Test Merchant ID** - IIprKr41695705075700

**Test Account Secret Key** - WOHWpJwW2iKN#tuJ

**Test Wallet Details**

Mobile Number - 77777 77777
Password          - Paytm12345
OTP                   - 489871


**Test Card Details**

Card Number	                  - Any Visa or Master Card
Expiration Month & Year	 - Any Future month and Year
CVV	                                  - 123
OTP	                                  - 123123

**Comment by anandsiddharth** [comment]
Cool thanx!
By the time you may want to star the repository :)

**Comment by cwdabba** [comment]
Sure I did it. Even I have done from another account. 

Thank you very much.

**Comment by anandsiddharth** [comment]
Hi @cwdabba I need `channel` , `website`  and `industry type` as well

**Comment by cwdabba** [comment]
@anandsiddharth  

CHANNEL_ID            - WEB
WEBSITE                   - WEBSTAGING
INDUSTRY_TYPE_ID - Retail

**Comment by anandsiddharth** [comment]
The credentials doesn't work for me, Did these credentials work for you with this package ?

**Comment by cwdabba** [comment]
Yes it works for me.

Please use phone no as 777777777

**Comment by anandsiddharth** [comment]
For me the, I am not able to reach checkout page of paytm.

can you post `services.php` here & is their any place in paytm dashboard where you need to specify authorized redirect urls?

**Comment by anandsiddharth** [comment]
The Issue was closed by mistake. This is not yet resolved. @cwdabba

**Comment by anandsiddharth** [comment]
This issue has been resolved.

https://github.com/anandsiddharth/laravel-paytm-wallet/commit/4ed3af48ca3b063304f9b88dba7c18916b4fa650


https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v1.0.10


Peace,
