### ISSUE TITLE
Modify transaction being processed page

### ISSUE THREAD

**Issue by aotearoait** [anandsiddharth/laravel-paytm-wallet#26]
Is there a way to modify the transaction being processed page as would like to make same design as rest of site.
Thanks

**Comment by anandsiddharth** [comment]
Hi @aotearoait 

Release v1.0.11 with custom view support ✌️ . Please star the repository if you find it useful.

https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v1.0.11

Docs: https://github.com/anandsiddharth/laravel-paytm-wallet#customizing-transaction-being-processed-page
