### ISSUE TITLE
Not redirecting to success page if payment made via UPI

### ISSUE THREAD

**Issue by cwdabba** [anandsiddharth/laravel-paytm-wallet#29]
Hi, When the user makes the payment via the UPI then it's not redirecting to the success URL. Can you please look into it.

**Comment by anandsiddharth** [comment]
Hi In staging merchant credentials I don't see an option for UPI Payment, If you are okay with sharing your merchent credentials share it to me privately on https://gitter.im/anandsiddharth

**Comment by cwdabba** [comment]
Hi if that was mine it would have been okay. Since its company's I can't disclose those. Is there any other way to work around. Really appreciate. Thanks

**Comment by anandsiddharth** [comment]
Well, I guess in my assumption Paytm has to take care of the redirection to the requested URL, try contacting paytm for info.

**Comment by cwdabba** [comment]
Hi, Do you check for the Bank Name in the PAYTM response if yes then can you please make it not mandatory for PAYTM UPI payments? If not then success URL is not called.

**Comment by anandsiddharth** [comment]
The code in this in this package does no extra validation!

**Comment by anandsiddharth** [comment]
You should contact paytm for that

**Comment by cwdabba** [comment]
Okay, thank you.

**Comment by cwdabba** [comment]
why do I get the Invalid checksum error in the following location

…/vendor/anandsiddharth/laravel-paytm-wallet/src/Providers/PaytmWalletProvider.php : 51

Can you please help me with this. This will solve the UPI payment issue for me.

**Comment by anandsiddharth** [comment]
Does the error come for other mode of payments ?

**Comment by cwdabba** [comment]
No. Only for this one.

**Comment by anandsiddharth** [comment]
Hmm! It's only for UPI, with staging merchant credentials they don't have UPI payment, I cannot debug without creds

**Comment by cwdabba** [comment]
I can share my friends production credentials will that be okay to test. If yes then please send the private message link. So that I can forward you the same.

**Comment by anandsiddharth** [comment]
https://gitter.im/anandsiddharth
