### ISSUE TITLE
PayTM return "Session expired due to inactivity"

### ISSUE THREAD

**Issue by nilpahar** [anandsiddharth/laravel-paytm-wallet#31]
You are lost in Space.
ORDER ID: 1553054551

Something went wrong. It may be due to any of these reasons:

Session expired due to inactivity
Our system encountered an obstacle

Visit us at paytm.com/care

**Comment by anandsiddharth** [comment]
https://github.com/anandsiddharth/laravel-paytm-wallet/issues/2

**Comment by nilpahar** [comment]
All config is corrent. But return this error

**Comment by golchha21** [comment]
The error that I am getting is

```
419
Sorry, your session has expired. Please refresh and try again.
```
I have gone through the duplicate of : #2 
but it does not solve the issue.
