### ISSUE TITLE
Laravel 6 Support.

### ISSUE THREAD

**Issue by InfoSecRavindra** [anandsiddharth/laravel-paytm-wallet#37]
I can see there is a pull request but it will break compatibility with Laravel 5 so what do you have in mind for Laravel 6 support?

**Comment by anandsiddharth** [comment]
Will figure out a workaround..

**Comment by anandsiddharth** [comment]
Done!
Here's a new release!
https://github.com/anandsiddharth/laravel-paytm-wallet/releases/tag/v1.0.13
