### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by Naveenanto** [anandsiddharth/laravel-paytm-wallet#4]
Function **mcrypt_module_open()** is deprecated as of PHP 7.1.0. Please Fix this asap. Thank you

**Comment by anandsiddharth** [comment]
in the package I have already mentioned that it uses official paytm sdk, as soons as they update the sdk i will update it this package

**Comment by anandsiddharth** [comment]
This issue is now resolved.
See this thread:
https://github.com/anandsiddharth/laravel-paytm-wallet/issues/8
