### ISSUE TITLE
Having this issue [screenshot] in Laravel 6

### ISSUE THREAD

**Issue by InfoSecRavindra** [anandsiddharth/laravel-paytm-wallet#40]
![Screenshot_20191002_181358](https://user-images.githubusercontent.com/22148496/66045030-83001880-e540-11e9-89ea-df5ac0cd0a34.png)

Changing private to protected solved issue.

**Comment by nitish1986** [comment]
Facing same issue. Is it fixed?

**Comment by InfoSecRavindra** [comment]
> Facing same issue. Is it fixed?

I have to update vendor folder to make it work.

**Comment by anandsiddharth** [comment]
Released v1.0.15

https://github.com/anandsiddharth/laravel-paytm-wallet/tree/v1.0.15
