### ISSUE TITLE
FatalErrorException in StatusCheckProvider.php line 6

### ISSUE THREAD

**Issue by itsavinash** [anandsiddharth/laravel-paytm-wallet#5]
Hi,

I am facing this issue whenever trying to access the StatusCheckProvider for and existing order.

FatalErrorException in StatusCheckProvider.php line 6:
Access level to Anand\LaravelPaytmWallet\Providers\StatusCheckProvider::$response must be protected (as in class Anand\LaravelPaytmWallet\Providers\PaytmWalletProvider) or weaker

**Comment by anandsiddharth** [comment]
hi @itsavinash 
Thanx for reporting! Just release a patch, update the package.

Peace

**Comment by debeniter86** [comment]
Hi,

I have updated composer update with
 "anandsiddharth/laravel-paytm-wallet": "1.0.3",
But it's not working. I am getting same error. Is there anything need to changed?
