### ISSUE TITLE
Laravel extra parameters

### ISSUE THREAD

**Issue by akhiidwandhare** [anandsiddharth/laravel-paytm-wallet#51]
Hey Buddy, I want to add some more extra parameters. Please guide me.

**Comment by anandsiddharth** [comment]
what parameters and where?

**Comment by akhiidwandhare** [comment]
I want to pass more parameters. like user name, provider id etc..

**Comment by anandsiddharth** [comment]
Please provide a minimum line of code to understand the issue, (the part where you integrate this package).

**Comment by akhiidwandhare** [comment]
$payment = PaytmWallet::with('receive');
        $payment->prepare([
          'order' => $order->id,
          'user' => $user->id,
          'mobile_number' => $user->phonenumber,
          'email' => $user->email,
          'amount' => $order->amount,
          'callback_url' => 'http://example.com/payment/status',
          'pro_id' => $id, //I want to add something like this
        ]);
        return $payment->receive();

**Comment by anandsiddharth** [comment]
No, you can't do that, because Paytm doesn't support that and there is no point in doing that because you have your own database, you can store it on your database or query from your database id already have it keeping order id as your reference.
