### ISSUE TITLE
composer install 404 issue

### ISSUE THREAD

**Issue by devmigi** [anandsiddharth/laravel-paytm-wallet#56]
Getting this issue while running composer command: 
`composer require anandsiddharth/laravel-paytm-wallet`

**Error**
`[Composer\Downloader\TransportException]                                                                                                                                                         
  The "https://packagist.org/p/anandsiddharth/laravel-paytm-wallet%24dd70fdd0534421543ecb322edded80c19d0c24275a2b83ebaa4d5c339807a463.json" file could not be downloaded (HTTP/1.1 404 Not Found)`

**Comment by anandsiddharth** [comment]
This issue is not specific to this package. You might have connectivity issue.
Try clearing composer cache
> `composer clearcache`
and then run 
> `composer require anandsiddharth/laravel-paytm-wallet`

**Comment by devmigi** [comment]
Thanks a lot :)
