### ISSUE TITLE
Not working in Laravel 8

### ISSUE THREAD

**Issue by RSCipher001** [anandsiddharth/laravel-paytm-wallet#58]
Here is the reason

URL: https://laravel.com/docs/8.x/upgrade

![Screenshot_20200924-121101_1.png](https://user-images.githubusercontent.com/22148496/94109809-28ea1880-fe5f-11ea-84c9-865707151671.png)

**Comment by dharmendrashah** [comment]
same

**Comment by anandsiddharth** [comment]
Hoping to fix this Sunday.
Meanwhile it would be great if someone shares staging/sandbox merchant details in discord
https://discord.gg/DA7XN5

**Comment by shubham110019** [comment]
Undefined property: Anand\LaravelPaytmWallet\PaytmWalletManager::$app

**Comment by sadique-cws** [comment]
> Undefined property: Anand\LaravelPaytmWallet\PaytmWalletManager::$app

Shubham replace **$this->app** with **$this->container**

**Manager $app Property**
The previously deprecated $app property of the Illuminate\Support\Manager class has been removed. If you were relying on this property, you should use the $container property instead.

**Comment by shubham110019** [comment]
thanx bro it's working
